---
title: 'Caso 1 - SINADEF'
author: "Estefanía Apaza"
date: "2026-05-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Agregamos la librería Tidyverse
library(tidyverse)

# Añadimos la semilla 123
set.seed(123)
```


```{r}
# Abrimos la base de datos en R
base1 <- read.csv("SINADEF_DATOS_ABIERTOS.csv")
```

```{r}
# Revisamos los nombres de las variables
names(base1)
```


```{r}
# Filtramos la base para los años 2019 y 2020

base_filtrada <- base1 %>%
  filter(ANIO %in% c(2019, 2020))
 
```

```{r}
# Realizamos el conteo de muertes por provincia y año agrupando las variables

MUERTES <- base_filtrada %>%
  group_by(PROVINCIA_FALLECIMIENTO, ANIO) %>%
  summarise(TOTAL_MUERTES = n())

```

```{r}
# Separamos las muertes por año

MUERTES_2019 <- MUERTES %>%
  filter(ANIO == 2019)

MUERTES_2020 <- MUERTES %>%
  filter(ANIO == 2020)

```

```{r}
# Unimos ambas tablas por provincia
BD_RATIOS <- merge(MUERTES_2019,
                MUERTES_2020,
                by = "PROVINCIA_FALLECIMIENTO")
```

```{r}
#Calculamos los ratios

BD_RATIOS <- BD_RATIOS %>%
  mutate(ratio = TOTAL_MUERTES.y / TOTAL_MUERTES.x)

```

```{r}
# Nos quedamos solo con provincia y ratio
BASE_SINADEF <- BD_RATIOS %>%
  select(PROVINCIA_FALLECIMIENTO, ratio)

# Revisamos que la base haya cargado bien los datos
head(BASE_SINADEF)

# Guardamos el archivo CSV
write.csv(BASE_SINADEF,
          "ratio_provincias.csv",
          row.names = FALSE)
```

```{r}
# ---
# Respuesta a preguntas
# ---
arrange(BASE_SINADEF, desc(ratio))
```
```{r}
# Pregunta 1:
# En Ocros se duplicó la tasa de mortalidad y no en Churcampa

BASE_SINADEF %>%
  filter(PROVINCIA_FALLECIMIENTO %in% c("CHURCAMPA", "OCROS"))

# FALSO. NO CALCULAMOS TASA DE MORTALIDAD SINO RATIO DE MUERTES.
```
```{r}
# Pregunta 2:
# En 23 provincias la tasa, al menos,se duplicó

BASE_SINADEF %>%
  filter(is.finite(ratio) & ratio >= 2) %>%
  nrow()

# VERDADERO
```

```{r}
# Pregunta 3:
# Hay solo una provincia con mortalidad atípica: Datem del Marañon

arrange(BASE_SINADEF, desc(ratio)) %>%
  head(10)

# FALSO
```

